### ISSUE TITLE
Doesn't appear to work with Electron 28

### ISSUE THREAD

**Issue by valsacar** [hurdlegroup/robotjs#19]
As the title says, just doesn't appear to work.

## Expected Behavior
Keytap sends key commands, mouse movement sends mouse movement

## Current Behavior
Tried mouse movement, key tap, etc.  None of them produce any output at all.

Primarily looking for keytap, but tried other aspects to see if it was just that part not working.  No errors show up, it just doesn't do anything.

Works fine on older versions of Electron/NodeJS.

## Possible Solution
?

## Steps to Reproduce (for bugs)

1. Install
2. Run
3. Nothing happens
4. Post here

## Your Environment

* RobotJS version: 0.11.4
* Node.js version: 21.7.2
* npm version: 10.5.1
* Operating System: Ubuntu 22.10 (tested on other OS as well)

**Comment by DanielMcAssey** [comment]
Unfortunately we do not support Electron 17, we support only the current stable versions of Electron

**Comment by valsacar** [comment]
Sorry... wrote that quickly in the morning, it is Electron 28 that we are currently using which isn't EOL until this summer.

**Comment by DanielMcAssey** [comment]
Ah gotcha, we have just released a new version that has a fix for mouse scroll and key tap, built against the latest Node, could you give that a go?

**Comment by valsacar** [comment]
I'm away from my computer most of the weekend, but I'll try and give it a go early next week.

**Comment by valsacar** [comment]
Sorry for the long delay, got busy with some other things.  Keytap still doesn't seem to be working for me.  If there's anyway to get robotjs to output some debug info that might help me confirm that is where the problem is for me.  Right now I can trace up to the call for keytap and everything is working as expected, but after that nothing.

**Comment by DanielMcAssey** [comment]
Ill see if I can add some debug or a debug build.

Does keyToggle followed by a delay (e.g. 100ms), then keyToggle for the same key work?

Additionally if on Windows, can you check the On-Screen keyboard when doing a keyToggle once, you should see the key pressed, then if you send keyToggle again, you should se it de-press

**Comment by DanielMcAssey** [comment]
@valsacar a new version is being built that fixes keyTap. When the version is released, let me know if it works. (related issue #22)
